import type { Metadata } from 'next';
import { DemoCta } from '@/components/DemoCta';
import { Callout, Card, ClaimList, Container, PageHeader, Section, TextLink } from '@/components/ui';
import { ACCESS_NOTICE, UPLOAD_NOTICE, siteConfig } from '@/lib/site';

export const metadata: Metadata = {
  title: 'Demonstration disclaimer',
  description:
    'What the Procurement Intelligence Demo interactive demonstration is, what data it uses, what it does not do, and what you must not enter into it.',
  alternates: { canonical: '/demo-disclaimer' },
};

export default function DemoDisclaimerPage() {
  return (
    <>
      <PageHeader
        eyebrow="Demonstration"
        title="Read this before using the interactive demonstration"
        lede="The short version: everything in it is fictional, uploads are currently disabled, the AI provider is a local mock, the application keeps no internal user accounts, and nothing you see has been validated against a real SAP system."
      >
        <DemoCta />
      </PageHeader>

      <Container>
        <Section title="Before you start">
          <Callout title="Do not enter any of the following" tone="warning">
            <p>
              The demonstration stores what you type in a shared database, and the application
              maintains no internal user accounts to partition it by visitor. Please do not enter:
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>confidential or commercially sensitive information</li>
              <li>personal information about yourself or anyone else</li>
              <li>medical, financial or otherwise regulated information</li>
              <li>real SAP data, system names, clients or credentials</li>
              <li>real supplier, purchase order, invoice or contract data</li>
              <li>proprietary company data of any kind</li>
            </ul>
            <p className="pt-2">
              File uploads are disabled server-side, not merely hidden - an upload request is
              refused by the API whether or not the button is on the page. Free-text fields
              remain, which is why this list matters.
            </p>
          </Callout>
        </Section>

        <Section title="Getting in, and what that does not mean">
          <div className="max-w-3xl space-y-4 text-slate-700 dark:text-slate-300">
            <p>{ACCESS_NOTICE}</p>
            <p>
              The public marketing website is open to anyone. The interactive demonstration sits on
              a separate hostname behind Cloudflare Access, and approved visitors authenticate
              through the configured Cloudflare Access method. That is a perimeter control over who
              reaches the demonstration - it is not per-user ownership of what is inside it.
            </p>
          </div>
        </Section>

        <Section title="What the demonstration is">
          <div className="grid gap-6 lg:grid-cols-2">
            <Card>
              <h3 className="text-lg font-semibold text-slate-900 dark:text-white">It is real</h3>
              <div className="mt-4">
                <ClaimList
                  variant="computed"
                  items={[
                    'The modules are the actual modules. The rules, scoring, matching, forecasting and marking are the real implementations.',
                    'The results are computed live from the bundled data, not recorded or replayed.',
                    'Every result carries its origin label, exactly as it does when the project is run locally.',
                    'Reports and exports are generated on request and can be downloaded.',
                  ]}
                />
              </div>
            </Card>
            <Card>
              <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
                And it is limited
              </h3>
              <div className="mt-4">
                <ClaimList
                  variant="plain"
                  items={[
                    'All data is fictional, generated by seeded scripts, with deliberately planted anomalies documented in manifests.',
                    'Uploads are currently disabled. Each module runs on its bundled dataset.',
                    'The AI provider is a local mock, selected before any provider key is consulted, so no text is sent to Anthropic, OpenAI or anyone else.',
                    'The application maintains no internal user accounts, roles or tenant permissions. Records created by one visitor may be visible to another through the API.',
                    'It runs on a single machine and may be unavailable for maintenance, updates or a restart.',
                    'The demonstration database may be reset at any time. Nothing in it should be treated as durable.',
                  ]}
                />
              </div>
            </Card>
          </div>
        </Section>

        <Section
          title="Different modules work in different ways"
          lede="A single sentence covering all ten would have to be either vague or wrong, so here is the distinction the origin label on each result makes."
        >
          <div className="max-w-3xl">
            <ClaimList
              variant="plain"
              items={[
                'Most results are deterministic: rules, thresholds, matching, weighted scoring, aggregation and rubric marking, all ordinary Python producing the same answer from the same input.',
                'Some results are statistical estimates rather than calculations - the demand forecasts, the stock projections and the shortage dates in the Inventory Predictor. They carry error and are labelled as forecasts.',
                'Some of the language is generated: executive summaries, explanations, answers to questions and drafted wording. It sits in its own fields and never changes a computed value.',
                'In this public demonstration that language comes from a local mock AI provider rather than a hosted model, and is labelled Mock AI where it appears.',
                'Every one of these requires human review before it is used for anything. Nothing here has been validated in a live SAP environment.',
              ]}
            />
            <p className="mt-6 text-slate-700 dark:text-slate-300">
              {UPLOAD_NOTICE} The full explanation of the split between calculation and language is
              on the <TextLink href="/how-it-works">how it works</TextLink> page.
            </p>
          </div>
        </Section>

        <Section title="Statements this project will not make">
          <div className="max-w-3xl">
            <ClaimList
              variant="plain"
              items={[
                'That any figure shown comes from a live SAP system. None does.',
                'That any recommendation has been validated in a live SAP environment. None has.',
                'That an estimated saving is a saving. Every savings figure is an estimate, labelled as one, and states the assumption it rests on.',
                'That a forecast is what will happen. It is a projection from history with error attached.',
                'That AI produced a number. In this platform it does not - and where a module says no AI touches a number, that is structural, not a promise.',
              ]}
            />
          </div>
        </Section>

        <Section title="Relationship to SAP">
          <p className="max-w-3xl text-slate-700 dark:text-slate-300">
            {siteConfig.name} is not an official SAP product. It is an independent demonstration
            project. SAP and SAP product names are trademarks of SAP SE or its affiliates. There is
            no endorsement, certification,
            sponsorship, partnership or affiliation, and no SAP logo, trademark, proprietary
            graphic or brand asset appears anywhere in this project. Read more on the{' '}
            <TextLink href="/about">about page</TextLink> and in the{' '}
            <TextLink href="/terms">terms and disclaimer</TextLink>.
          </p>
        </Section>
      </Container>
    </>
  );
}
