"""Loading, validating and indexing the bundled interview question bank.

The bank lives in ``data/sample/sample_interview_questions.json`` because it is
demo content: every question, every company and every scenario in it is
fictional. It is committed, so a fresh clone can run an interview immediately,
and it is regenerated by ``scripts/generate_interview_sample_data.py``.

Two things happen here that a plain ``json.load`` would not do:

* **The bank is validated as a contract, not just as JSON.** Pydantic checks the
  shape; :func:`_check_bank_contract` then checks the things that make a rubric
  usable - that identifiers are unique, that every question can be scored on
  technical accuracy *and* on business understanding, that a question offered in
  architecture mode actually carries architecture concepts, and that every
  follow-up which claims to target a concept targets one that exists. A bank
  that fails any of these is rejected at load time rather than producing a
  question that silently cannot be marked on half its dimensions.
* **Every question gets a rubric fingerprint.** A score is a verdict about a
  rubric, so each stored answer records the fingerprint of the rubric it was
  marked against. When the bank is retuned the old scores are kept and flagged
  rather than quietly averaging into a dashboard alongside scores that were
  earned under different rules.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any

from pydantic import ValidationError as PydanticValidationError

from app.core.config import settings
from app.core.exceptions import ConfigurationError, NotFoundError
from app.core.logging import get_logger
from app.schemas.interview_coach import (
    DIFFICULTY_ORDER,
    MODE_ORDER,
    TRACK_ORDER,
    AnswerKeySchema,
    BankQuestionSchema,
    ConceptDimension,
    InterviewMode,
    InterviewQuestionSchema,
    InterviewTrack,
    QuestionBankInfoSchema,
    QuestionBankSchema,
    QuestionDifficulty,
)

logger = get_logger(__name__)

QUESTION_BANK_FILE = "sample_interview_questions.json"
MANIFEST_FILE = "interview_scenario_manifest.json"

#: How many characters of the rubric digest are kept. Sixteen hex characters is
#: far more than enough to notice a retune and short enough to print.
FINGERPRINT_CHARS = 16


def _check_bank_contract(bank: QuestionBankSchema) -> None:
    """Raise when a structurally valid bank could not actually be marked."""
    problems: list[str] = []
    seen_ids: set[str] = set()

    for question in bank.questions:
        qid = question.question_id
        if qid in seen_ids:
            problems.append(f"{qid}: duplicate question_id")
        seen_ids.add(qid)

        concept_ids = {concept.concept_id for concept in question.expected_concepts}
        if len(concept_ids) != len(question.expected_concepts):
            problems.append(f"{qid}: two expected concepts share a concept_id")

        dimensions = {concept.dimension for concept in question.expected_concepts}
        if ConceptDimension.TECHNICAL not in dimensions:
            problems.append(f"{qid}: no technical concept, so technical accuracy cannot be scored")
        if ConceptDimension.BUSINESS not in dimensions:
            problems.append(
                f"{qid}: no business concept, so business understanding cannot be scored"
            )
        if (
            InterviewMode.ARCHITECTURE in question.modes
            and ConceptDimension.ARCHITECTURE not in dimensions
        ):
            problems.append(
                f"{qid}: offered in architecture mode but carries no architecture concept"
            )

        for follow_up in question.follow_up_questions:
            if follow_up.targets_concept_id and follow_up.targets_concept_id not in concept_ids:
                problems.append(
                    f"{qid}: follow-up targets unknown concept "
                    f"'{follow_up.targets_concept_id}'"
                )

        statement_ids = {item.statement_id for item in question.incorrect_statements}
        if len(statement_ids) != len(question.incorrect_statements):
            problems.append(f"{qid}: two incorrect statements share a statement_id")

    if problems:
        raise ConfigurationError(
            f"The interview question bank failed its contract checks: {len(problems)} problem(s).",
            details={"problems": problems[:20]},
        )


def rubric_fingerprint(question: BankQuestionSchema) -> str:
    """Return a short digest of everything that decides this question's score.

    Only the marking-relevant fields go in. Fixing a typo in the question text
    or adding a follow-up does not invalidate a score that was already given;
    changing a keyword list, a weight or a penalty does.
    """
    payload = {
        "concepts": [
            {
                "id": concept.concept_id,
                "dimension": concept.dimension.value,
                "weight": concept.weight,
                "required": concept.required,
                "keywords": sorted(keyword.lower() for keyword in concept.keywords),
                "negations": sorted(item.lower() for item in concept.negation_patterns),
            }
            for concept in sorted(question.expected_concepts, key=lambda item: item.concept_id)
        ],
        "incorrect": [
            {
                "id": item.statement_id,
                "patterns": sorted(pattern.lower() for pattern in item.patterns),
                "penalty": item.penalty_points,
            }
            for item in sorted(question.incorrect_statements, key=lambda item: item.statement_id)
        ],
        "weights": {
            dimension.value: weight for dimension, weight in sorted(
                question.rubric.weights.items(), key=lambda pair: pair[0].value
            )
        },
        "pass_score": question.rubric.pass_score,
    }
    serialised = json.dumps(payload, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(serialised.encode("utf-8")).hexdigest()[:FINGERPRINT_CHARS]


@dataclass
class QuestionBank:
    """The validated question bank with the indexes the selector needs."""

    bank_version: str
    description: str = ""
    manifest: str | None = None
    questions: list[BankQuestionSchema] = field(default_factory=list)
    _by_id: dict[str, BankQuestionSchema] = field(default_factory=dict, repr=False)
    _fingerprints: dict[str, str] = field(default_factory=dict, repr=False)

    @classmethod
    def from_schema(cls, schema: QuestionBankSchema) -> QuestionBank:
        """Build the indexed bank from a validated payload."""
        bank = cls(
            bank_version=schema.bank_version,
            description=schema.description,
            manifest=schema.manifest,
            questions=list(schema.questions),
        )
        bank._by_id = {question.question_id: question for question in schema.questions}
        bank._fingerprints = {
            question.question_id: rubric_fingerprint(question) for question in schema.questions
        }
        return bank

    # -- lookups ---------------------------------------------------------
    def get(self, question_id: str) -> BankQuestionSchema:
        """Return one question, or raise :class:`NotFoundError`."""
        question = self._by_id.get(question_id)
        if question is None:
            raise NotFoundError(
                "That interview question is not in the bundled question bank.",
                details={"question_id": question_id},
            )
        return question

    def find(self, question_id: str) -> BankQuestionSchema | None:
        """Return one question, or ``None`` when the bank no longer has it."""
        return self._by_id.get(question_id)

    def fingerprint(self, question_id: str) -> str:
        """Return the rubric fingerprint of one question (empty when unknown)."""
        return self._fingerprints.get(question_id, "")

    def matching(
        self,
        *,
        tracks: list[InterviewTrack] | None = None,
        mode: InterviewMode | None = None,
        difficulties: list[QuestionDifficulty] | None = None,
        topics: list[str] | None = None,
    ) -> list[BankQuestionSchema]:
        """Return every question matching the filters, in bank order."""
        wanted_tracks = set(tracks) if tracks else None
        wanted_difficulties = set(difficulties) if difficulties else None
        wanted_topics = {topic.strip().lower() for topic in topics} if topics else None

        results: list[BankQuestionSchema] = []
        for question in self.questions:
            if wanted_tracks is not None and question.track not in wanted_tracks:
                continue
            if mode is not None and mode not in question.modes:
                continue
            if wanted_difficulties is not None and question.difficulty not in wanted_difficulties:
                continue
            if wanted_topics is not None and question.topic.strip().lower() not in wanted_topics:
                continue
            results.append(question)
        return results

    def topics(self, track: InterviewTrack | None = None) -> list[str]:
        """Return the distinct topics, optionally for one track, sorted."""
        return sorted(
            {
                question.topic
                for question in self.questions
                if track is None or question.track is track
            }
        )

    def topic_track(self, topic: str) -> InterviewTrack | None:
        """Return the track a topic belongs to, when it belongs to exactly one."""
        tracks = {
            question.track
            for question in self.questions
            if question.topic.strip().lower() == topic.strip().lower()
        }
        return next(iter(tracks)) if len(tracks) == 1 else None

    # -- presentation ----------------------------------------------------
    def public_question(
        self, question: BankQuestionSchema, *, time_limit_seconds: int | None = None
    ) -> InterviewQuestionSchema:
        """Return the candidate-facing view: the question without its answer key."""
        return InterviewQuestionSchema(
            question_id=question.question_id,
            track=question.track,
            topic=question.topic,
            difficulty=question.difficulty,
            modes=list(question.modes),
            question=question.question,
            rubric_summary=question.rubric.summary,
            expected_concept_count=len(question.expected_concepts),
            time_limit_seconds=time_limit_seconds,
            tags=list(question.tags),
        )

    def answer_key(self, question: BankQuestionSchema) -> AnswerKeySchema:
        """Return the marking scheme, shown only after an answer is submitted."""
        return AnswerKeySchema(
            question_id=question.question_id,
            expected_concepts=list(question.expected_concepts),
            incorrect_statements=list(question.incorrect_statements),
            follow_up_questions=list(question.follow_up_questions),
            reference_answer=question.reference_answer,
            rubric=question.rubric,
            study_topics=list(question.study_topics),
        )

    def info(self) -> QuestionBankInfoSchema:
        """Describe the bank for the catalogue and the UI."""
        by_track: dict[str, int] = {}
        by_difficulty: dict[str, int] = {}
        by_mode: dict[str, int] = {}
        for question in self.questions:
            by_track[question.track.value] = by_track.get(question.track.value, 0) + 1
            by_difficulty[question.difficulty.value] = (
                by_difficulty.get(question.difficulty.value, 0) + 1
            )
            for mode in question.modes:
                by_mode[mode.value] = by_mode.get(mode.value, 0) + 1

        return QuestionBankInfoSchema(
            available=True,
            bank_version=self.bank_version,
            question_count=len(self.questions),
            by_track={
                track.value: by_track.get(track.value, 0)
                for track in TRACK_ORDER
                if by_track.get(track.value)
            },
            by_difficulty={
                difficulty.value: by_difficulty.get(difficulty.value, 0)
                for difficulty in DIFFICULTY_ORDER
                if by_difficulty.get(difficulty.value)
            },
            by_mode={
                mode.value: by_mode.get(mode.value, 0)
                for mode in MODE_ORDER
                if by_mode.get(mode.value)
            },
            topics=self.topics(),
            manifest=self.manifest,
        )


def bank_path() -> Path:
    """Return the path of the bundled question bank."""
    return settings.sample_dir / QUESTION_BANK_FILE


def load_question_bank(path: Path | str | None = None) -> QuestionBank:
    """Load, validate and index the question bank from ``path``."""
    file_path = Path(path) if path else bank_path()
    if not file_path.is_file():
        raise ConfigurationError(
            "The interview question bank has not been generated yet. Run: "
            "python scripts/generate_interview_sample_data.py",
            details={"expected_file": QUESTION_BANK_FILE},
        )
    try:
        raw: Any = json.loads(file_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ConfigurationError(
            f"The interview question bank is not valid JSON: {exc.msg} (line {exc.lineno})"
        ) from exc

    try:
        schema = QuestionBankSchema.model_validate(raw)
    except PydanticValidationError as exc:
        raise ConfigurationError(
            f"The interview question bank failed validation: {exc.error_count()} problem(s).",
            details={"errors": exc.errors(include_url=False)[:10]},
        ) from exc

    _check_bank_contract(schema)
    bank = QuestionBank.from_schema(schema)
    logger.info(
        "Loaded interview question bank v%s (%d questions)",
        bank.bank_version,
        len(bank.questions),
    )
    return bank


@lru_cache(maxsize=1)
def get_question_bank() -> QuestionBank:
    """Return the cached bundled question bank."""
    return load_question_bank()


def question_bank_available() -> bool:
    """Return ``True`` when the bundled bank exists and loads."""
    try:
        get_question_bank()
    except ConfigurationError:
        return False
    return True
