/**
 * The five output origins, described for a reader rather than a schema.
 *
 * These mirror `app/schemas/common.py::OutputOrigin`. Every result the platform
 * shows carries one of them, and the whole point of the labelling is that a
 * reader can tell a computed number from a sentence a model wrote. Explaining
 * the difference on the website is part of making that true rather than
 * decorative.
 */

import type { OutputOrigin } from './modules';

export interface OriginDescription {
  origin: OutputOrigin;
  label: string;
  summary: string;
  detail: string;
  /** Tailwind classes for the badge. Kept next to the meaning they encode. */
  className: string;
}

export const origins: readonly OriginDescription[] = [
  {
    origin: 'rule_based',
    label: 'Rule-based',
    summary: 'Calculated by ordinary Python from the data.',
    detail:
      'A finding, a score, a match or an aggregate produced by configured rules reading the ' +
      'input. Reproducible: the same file always gives the same answer. Thresholds live in ' +
      'JSON configuration, so changing what counts as risky is an edit rather than a code ' +
      'change.',
    className:
      'bg-sky-100 text-sky-900 ring-sky-600/20 dark:bg-sky-950 dark:text-sky-200 dark:ring-sky-400/30',
  },
  {
    origin: 'forecast',
    label: 'Forecast',
    summary: 'A statistical projection, not a fact about the future.',
    detail:
      'Produced by a model chosen through backtesting on held-out periods. It reports which ' +
      'model won and why. A projection is an estimate with error attached, and it is labelled ' +
      'separately from a rule result so nobody reads one as the other.',
    className:
      'bg-violet-100 text-violet-900 ring-violet-600/20 dark:bg-violet-950 dark:text-violet-200 dark:ring-violet-400/30',
  },
  {
    origin: 'ai_generated',
    label: 'AI-generated',
    summary: 'Written by a language model, about results code produced.',
    detail:
      'Explanation, summary and drafting only. AI text lives in its own fields and never ' +
      'overwrites a computed value. Where AI drafts an artefact - a test case, a blueprint ' +
      'section - the structure around it was decided by code first.',
    className:
      'bg-amber-100 text-amber-900 ring-amber-600/20 dark:bg-amber-950 dark:text-amber-200 dark:ring-amber-400/30',
  },
  {
    origin: 'mock_ai',
    label: 'Mock AI',
    summary: 'Generated locally from the computed results. No provider was called.',
    detail:
      'The default. With no API key configured, the platform composes narrative text from the ' +
      'rule output instead of contacting a provider, so every module runs end to end with no ' +
      'credentials and no cost. The public demonstration always runs in this mode.',
    className:
      'bg-slate-200 text-slate-900 ring-slate-600/20 dark:bg-slate-800 dark:text-slate-200 dark:ring-slate-400/30',
  },
  {
    origin: 'demo_data',
    label: 'Demonstration data',
    summary: 'Fictional sample data, generated for this project.',
    detail:
      'Every supplier, purchase order, invoice, contract and material here was generated by a ' +
      'seeded script. The anomalies in each dataset are deliberate and documented in a ' +
      'manifest, so a result can be checked against a known expectation. None of it came from ' +
      'a real company or a real SAP system.',
    className:
      'bg-emerald-100 text-emerald-900 ring-emerald-600/20 dark:bg-emerald-950 dark:text-emerald-200 dark:ring-emerald-400/30',
  },
] as const;

export function originByKey(key: OutputOrigin): OriginDescription {
  const found = origins.find((entry) => entry.origin === key);
  if (!found) {
    throw new Error(`Unknown output origin: ${key}`);
  }
  return found;
}
