"""initial po risk schema

Revision ID: 02d5339cd4ee
Revises: 
Create Date: 2026-07-31 01:46:21.205164
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '02d5339cd4ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=300), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('detected_columns', sa.JSON(), nullable=False),
    sa.Column('suggested_mapping', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_files'))
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_sha256'), ['sha256'], unique=False)

    op.create_table('po_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('config_version', sa.String(length=20), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('applied_mapping', sa.JSON(), nullable=False),
    sa.Column('unmapped_columns', sa.JSON(), nullable=False),
    sa.Column('data_quality_issues', sa.JSON(), nullable=False),
    sa.Column('kpis', sa.JSON(), nullable=False),
    sa.Column('supplier_risk', sa.JSON(), nullable=False),
    sa.Column('rule_executions', sa.JSON(), nullable=False),
    sa.Column('rule_errors', sa.JSON(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('purchase_order_count', sa.Integer(), nullable=False),
    sa.Column('supplier_count', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('flagged_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('estimated_exposure', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('ai_provider', sa.String(length=30), nullable=True),
    sa.Column('ai_output_origin', sa.String(length=20), nullable=True),
    sa.Column('ai_prompt_version', sa.String(length=20), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_key_risks', sa.JSON(), nullable=False),
    sa.Column('ai_recommended_actions', sa.JSON(), nullable=False),
    sa.Column('ai_input_tokens', sa.Integer(), nullable=True),
    sa.Column('ai_output_tokens', sa.Integer(), nullable=True),
    sa.Column('ai_estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('ai_error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_files.id'], name=op.f('fk_po_analyses_upload_id_uploaded_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_po_analyses'))
    )
    with op.batch_alter_table('po_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_po_analyses_upload_id'), ['upload_id'], unique=False)

    op.create_table('po_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=20), nullable=True),
    sa.Column('po_item', sa.String(length=10), nullable=True),
    sa.Column('supplier_id', sa.String(length=20), nullable=True),
    sa.Column('supplier_name', sa.String(length=120), nullable=True),
    sa.Column('risk_category', sa.String(length=60), nullable=False),
    sa.Column('rule_id', sa.String(length=20), nullable=False),
    sa.Column('rule_name', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('estimated_financial_exposure', sa.Float(), nullable=False),
    sa.Column('exposure_currency', sa.String(length=3), nullable=False),
    sa.Column('output_origin', sa.String(length=20), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('ai_recommended_action', sa.Text(), nullable=True),
    sa.Column('ai_output_origin', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['po_analyses.id'], name=op.f('fk_po_findings_analysis_id_po_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_po_findings'))
    )
    with op.batch_alter_table('po_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_findings_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index('ix_po_findings_analysis_severity', ['analysis_id', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_po_findings_po_number'), ['po_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_po_findings_risk_category'), ['risk_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_po_findings_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_po_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_po_findings_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('po_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=20), nullable=True),
    sa.Column('po_item', sa.String(length=10), nullable=True),
    sa.Column('supplier_id', sa.String(length=20), nullable=True),
    sa.Column('supplier_name', sa.String(length=120), nullable=True),
    sa.Column('material', sa.String(length=40), nullable=True),
    sa.Column('material_description', sa.String(length=255), nullable=True),
    sa.Column('material_group', sa.String(length=20), nullable=True),
    sa.Column('company_code', sa.String(length=10), nullable=True),
    sa.Column('purchasing_org', sa.String(length=10), nullable=True),
    sa.Column('purchasing_group', sa.String(length=10), nullable=True),
    sa.Column('plant', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=10), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('total_value_base', sa.Float(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('requested_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('contract_number', sa.String(length=20), nullable=True),
    sa.Column('payment_terms', sa.String(length=20), nullable=True),
    sa.Column('approval_status', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('changed_by', sa.String(length=30), nullable=True),
    sa.Column('change_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['po_analyses.id'], name=op.f('fk_po_records_analysis_id_po_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_po_records'))
    )
    with op.batch_alter_table('po_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_records_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index('ix_po_records_analysis_po', ['analysis_id', 'po_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_po_records_material'), ['material'], unique=False)
        batch_op.create_index(batch_op.f('ix_po_records_po_number'), ['po_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_po_records_supplier_id'), ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_po_records_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_po_records_po_number'))
        batch_op.drop_index(batch_op.f('ix_po_records_material'))
        batch_op.drop_index('ix_po_records_analysis_po')
        batch_op.drop_index(batch_op.f('ix_po_records_analysis_id'))

    op.drop_table('po_records')
    with op.batch_alter_table('po_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_po_findings_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_po_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_po_findings_rule_id'))
        batch_op.drop_index(batch_op.f('ix_po_findings_risk_category'))
        batch_op.drop_index(batch_op.f('ix_po_findings_po_number'))
        batch_op.drop_index('ix_po_findings_analysis_severity')
        batch_op.drop_index(batch_op.f('ix_po_findings_analysis_id'))

    op.drop_table('po_findings')
    with op.batch_alter_table('po_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_po_analyses_upload_id'))
        batch_op.drop_index(batch_op.f('ix_po_analyses_created_at'))

    op.drop_table('po_analyses')
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_sha256'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_created_at'))

    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
