"""spend analytics schema

Revision ID: 3c761d0c43df
Revises: 02d5339cd4ee
Create Date: 2026-07-31 03:05:00.836103
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c761d0c43df'
down_revision: Union[str, None] = '02d5339cd4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spend_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('config_version', sa.String(length=20), nullable=False),
    sa.Column('metrics_version', sa.String(length=20), nullable=False),
    sa.Column('savings_engine_version', sa.String(length=20), nullable=False),
    sa.Column('applied_mapping', sa.JSON(), nullable=False),
    sa.Column('unmapped_columns', sa.JSON(), nullable=False),
    sa.Column('data_quality_issues', sa.JSON(), nullable=False),
    sa.Column('applied_filter', sa.JSON(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('filtered_record_count', sa.Integer(), nullable=False),
    sa.Column('purchase_order_count', sa.Integer(), nullable=False),
    sa.Column('supplier_count', sa.Integer(), nullable=False),
    sa.Column('contracted_spend', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('maverick_spend', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tail_spend', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('spend_under_management_pct', sa.Float(), nullable=False),
    sa.Column('supplier_concentration_hhi', sa.Float(), nullable=False),
    sa.Column('estimated_savings', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('opportunity_count', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('analytics', sa.JSON(), nullable=False),
    sa.Column('supplier_spend', sa.JSON(), nullable=False),
    sa.Column('savings_executions', sa.JSON(), nullable=False),
    sa.Column('savings_errors', sa.JSON(), nullable=False),
    sa.Column('filter_options', sa.JSON(), nullable=False),
    sa.Column('ai_provider', sa.String(length=30), nullable=True),
    sa.Column('ai_output_origin', sa.String(length=20), nullable=True),
    sa.Column('ai_prompt_version', sa.String(length=30), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_key_findings', sa.JSON(), nullable=False),
    sa.Column('ai_recommended_actions', sa.JSON(), nullable=False),
    sa.Column('ai_input_tokens', sa.Integer(), nullable=True),
    sa.Column('ai_output_tokens', sa.Integer(), nullable=True),
    sa.Column('ai_estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('ai_error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_files.id'], name=op.f('fk_spend_analyses_upload_id_uploaded_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spend_analyses'))
    )
    with op.batch_alter_table('spend_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spend_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_analyses_upload_id'), ['upload_id'], unique=False)

    op.create_table('spend_opportunities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=20), nullable=False),
    sa.Column('rule_name', sa.String(length=120), nullable=False),
    sa.Column('opportunity_type', sa.String(length=60), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('scope_value', sa.String(length=120), nullable=False),
    sa.Column('scope_label', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('addressable_spend_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_saving_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realization_factor', sa.Float(), nullable=False),
    sa.Column('estimated_saving_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('supplier_count', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['spend_analyses.id'], name=op.f('fk_spend_opportunities_analysis_id_spend_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spend_opportunities'))
    )
    with op.batch_alter_table('spend_opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spend_opportunities_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_opportunities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_opportunities_opportunity_type'), ['opportunity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_opportunities_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_opportunities_scope_value'), ['scope_value'], unique=False)

    op.create_table('spend_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=20), nullable=True),
    sa.Column('po_item', sa.String(length=10), nullable=True),
    sa.Column('supplier_id', sa.String(length=20), nullable=True),
    sa.Column('supplier_name', sa.String(length=120), nullable=True),
    sa.Column('material', sa.String(length=40), nullable=True),
    sa.Column('material_description', sa.String(length=255), nullable=True),
    sa.Column('material_group', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('subcategory', sa.String(length=80), nullable=True),
    sa.Column('company_code', sa.String(length=10), nullable=True),
    sa.Column('purchasing_org', sa.String(length=10), nullable=True),
    sa.Column('purchasing_group', sa.String(length=10), nullable=True),
    sa.Column('plant', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=10), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('baseline_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('spend_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('spend_month', sa.String(length=7), nullable=True),
    sa.Column('contract_number', sa.String(length=20), nullable=True),
    sa.Column('contract_status', sa.String(length=40), nullable=True),
    sa.Column('preferred_supplier_status', sa.String(length=40), nullable=True),
    sa.Column('payment_status', sa.String(length=40), nullable=True),
    sa.Column('is_contracted', sa.Boolean(), nullable=False),
    sa.Column('is_preferred_supplier', sa.Boolean(), nullable=False),
    sa.Column('is_maverick', sa.Boolean(), nullable=False),
    sa.Column('is_under_management', sa.Boolean(), nullable=False),
    sa.Column('price_variance_base', sa.Float(), nullable=True),
    sa.Column('price_variance_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['spend_analyses.id'], name=op.f('fk_spend_transactions_analysis_id_spend_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spend_transactions'))
    )
    with op.batch_alter_table('spend_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spend_transactions_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_transactions_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_transactions_is_contracted'), ['is_contracted'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_transactions_is_maverick'), ['is_maverick'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_transactions_material'), ['material'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_transactions_material_group'), ['material_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_transactions_po_number'), ['po_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_transactions_spend_month'), ['spend_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_transactions_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index('ix_spend_tx_analysis_category', ['analysis_id', 'category'], unique=False)
        batch_op.create_index('ix_spend_tx_analysis_month', ['analysis_id', 'spend_month'], unique=False)
        batch_op.create_index('ix_spend_tx_analysis_supplier', ['analysis_id', 'supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spend_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_spend_tx_analysis_supplier')
        batch_op.drop_index('ix_spend_tx_analysis_month')
        batch_op.drop_index('ix_spend_tx_analysis_category')
        batch_op.drop_index(batch_op.f('ix_spend_transactions_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_spend_transactions_spend_month'))
        batch_op.drop_index(batch_op.f('ix_spend_transactions_po_number'))
        batch_op.drop_index(batch_op.f('ix_spend_transactions_material_group'))
        batch_op.drop_index(batch_op.f('ix_spend_transactions_material'))
        batch_op.drop_index(batch_op.f('ix_spend_transactions_is_maverick'))
        batch_op.drop_index(batch_op.f('ix_spend_transactions_is_contracted'))
        batch_op.drop_index(batch_op.f('ix_spend_transactions_effective_date'))
        batch_op.drop_index(batch_op.f('ix_spend_transactions_category'))
        batch_op.drop_index(batch_op.f('ix_spend_transactions_analysis_id'))

    op.drop_table('spend_transactions')
    with op.batch_alter_table('spend_opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spend_opportunities_scope_value'))
        batch_op.drop_index(batch_op.f('ix_spend_opportunities_rule_id'))
        batch_op.drop_index(batch_op.f('ix_spend_opportunities_opportunity_type'))
        batch_op.drop_index(batch_op.f('ix_spend_opportunities_created_at'))
        batch_op.drop_index(batch_op.f('ix_spend_opportunities_analysis_id'))

    op.drop_table('spend_opportunities')
    with op.batch_alter_table('spend_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spend_analyses_upload_id'))
        batch_op.drop_index(batch_op.f('ix_spend_analyses_created_at'))

    op.drop_table('spend_analyses')
    # ### end Alembic commands ###
