"""supplier recommendation schema

Revision ID: a16bad79dd24
Revises: 3c761d0c43df
Create Date: 2026-07-31 04:47:36.133312
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a16bad79dd24'
down_revision: str | None = '3c761d0c43df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_catalogs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('config_version', sa.String(length=20), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('applied_mapping', sa.JSON(), nullable=False),
    sa.Column('unmapped_columns', sa.JSON(), nullable=False),
    sa.Column('data_quality_issues', sa.JSON(), nullable=False),
    sa.Column('supplier_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_files.id'], name=op.f('fk_supplier_catalogs_upload_id_uploaded_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_catalogs'))
    )
    with op.batch_alter_table('supplier_catalogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_catalogs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_catalogs_upload_id'), ['upload_id'], unique=False)

    op.create_table('supplier_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('catalog_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('config_version', sa.String(length=20), nullable=False),
    sa.Column('scoring_engine_version', sa.String(length=20), nullable=False),
    sa.Column('requirement', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('total_supplier_count', sa.Integer(), nullable=False),
    sa.Column('eligible_count', sa.Integer(), nullable=False),
    sa.Column('ineligible_count', sa.Integer(), nullable=False),
    sa.Column('top_supplier_id', sa.String(length=20), nullable=True),
    sa.Column('top_supplier_score', sa.Float(), nullable=True),
    sa.Column('ai_provider', sa.String(length=30), nullable=True),
    sa.Column('ai_output_origin', sa.String(length=20), nullable=True),
    sa.Column('ai_prompt_version', sa.String(length=30), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_key_findings', sa.JSON(), nullable=False),
    sa.Column('ai_recommended_actions', sa.JSON(), nullable=False),
    sa.Column('ai_input_tokens', sa.Integer(), nullable=True),
    sa.Column('ai_output_tokens', sa.Integer(), nullable=True),
    sa.Column('ai_estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('ai_error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['supplier_catalogs.id'], name=op.f('fk_supplier_recommendations_catalog_id_supplier_catalogs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_recommendations'))
    )
    with op.batch_alter_table('supplier_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_recommendations_catalog_id'), ['catalog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_recommendations_created_at'), ['created_at'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('catalog_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(length=20), nullable=False),
    sa.Column('supplier_name', sa.String(length=120), nullable=True),
    sa.Column('materials_supplied', sa.JSON(), nullable=False),
    sa.Column('plants_served', sa.JSON(), nullable=False),
    sa.Column('regions_served', sa.JSON(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('unit_price_base', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('available_capacity', sa.Float(), nullable=True),
    sa.Column('on_time_delivery_rate', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('defect_rate', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('esg_score', sa.Float(), nullable=True),
    sa.Column('contract_status', sa.String(length=40), nullable=True),
    sa.Column('contract_expiration', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=20), nullable=True),
    sa.Column('historical_order_count', sa.Integer(), nullable=True),
    sa.Column('historical_spend', sa.Float(), nullable=True),
    sa.Column('historical_spend_base', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['supplier_catalogs.id'], name=op.f('fk_suppliers_catalog_id_supplier_catalogs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_catalog_id'), ['catalog_id'], unique=False)
        batch_op.create_index('ix_suppliers_catalog_supplier', ['catalog_id', 'supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('supplier_recommendation_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=20), nullable=False),
    sa.Column('supplier_name', sa.String(length=120), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('eligibility_status', sa.String(length=20), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('cost_score', sa.Float(), nullable=False),
    sa.Column('delivery_score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('capacity_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('esg_score', sa.Float(), nullable=False),
    sa.Column('contract_score', sa.Float(), nullable=False),
    sa.Column('geographic_score', sa.Float(), nullable=False),
    sa.Column('past_performance_score', sa.Float(), nullable=False),
    sa.Column('estimated_unit_price_base', sa.Float(), nullable=True),
    sa.Column('estimated_total_cost_base', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('estimated_delivery_date', sa.Date(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('contract_status', sa.String(length=40), nullable=True),
    sa.Column('contract_classification', sa.String(length=20), nullable=True),
    sa.Column('advantages', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('ineligibility_reasons', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['supplier_recommendations.id'], name=op.f('fk_supplier_recommendation_entries_recommendation_id_supplier_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_recommendation_entries'))
    )
    with op.batch_alter_table('supplier_recommendation_entries', schema=None) as batch_op:
        batch_op.create_index('ix_reco_entry_reco_rank', ['recommendation_id', 'rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_recommendation_entries_is_eligible'), ['is_eligible'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_recommendation_entries_rank'), ['rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_recommendation_entries_recommendation_id'), ['recommendation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_recommendation_entries_supplier_id'), ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_recommendation_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_recommendation_entries_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_recommendation_entries_recommendation_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_recommendation_entries_rank'))
        batch_op.drop_index(batch_op.f('ix_supplier_recommendation_entries_is_eligible'))
        batch_op.drop_index('ix_reco_entry_reco_rank')

    op.drop_table('supplier_recommendation_entries')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_supplier_id'))
        batch_op.drop_index('ix_suppliers_catalog_supplier')
        batch_op.drop_index(batch_op.f('ix_suppliers_catalog_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('supplier_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_recommendations_created_at'))
        batch_op.drop_index(batch_op.f('ix_supplier_recommendations_catalog_id'))

    op.drop_table('supplier_recommendations')
    with op.batch_alter_table('supplier_catalogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_catalogs_upload_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_catalogs_created_at'))

    op.drop_table('supplier_catalogs')
    # ### end Alembic commands ###
