#!/usr/bin/env bash
#
# Restore the SAPDemo demonstration database from a backup.
#
#   ./scripts/restore_selfhosted.sh --file backups/sapdemo-....dump
#   ./scripts/restore_selfhosted.sh --file ... --into-throwaway   # verify only
#   ./scripts/restore_selfhosted.sh --latest                      # newest backup
#
# Two modes, and the difference matters:
#
#   default            replaces the live demonstration database. Destructive.
#                      Requires an interactive confirmation typed in full.
#   --into-throwaway   restores into a temporary database that is dropped
#                      afterwards. Touches nothing live. This is what
#                      `backup_selfhosted.sh --verify` calls, and it is how you
#                      find out whether a backup works *before* you need it.
#
# The checksum is verified before anything is restored. A dump that fails its
# checksum is refused rather than partially applied - a half-restored database
# is worse than a stopped one, because it looks like it worked.
#
# Exit codes:
#   0  restored (or verified) successfully
#   1  a step failed
#   2  refused (bad arguments, failed checksum, no confirmation)

. "$(cd "$(dirname "$0")" && pwd)/lib/selfhosted.sh"

FILE=""
THROWAWAY=0
ASSUME_YES=0
LATEST=0

while [ "$#" -gt 0 ]; do
    case "$1" in
        --file) shift; FILE="${1:-}" ;;
        --latest) LATEST=1 ;;
        --into-throwaway) THROWAWAY=1 ;;
        --yes|-y) ASSUME_YES=1 ;;
        -h|--help) sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) die "Unknown option: $1. Try --help." 2 ;;
    esac
    shift
done

info "SAPDemo - restoring the demonstration database"
require_docker
validate_env || die "Fix ${ENV_FILE} and try again." 2

db_name="$(env_value POSTGRES_DB)"
db_user="$(env_value POSTGRES_USER)"

if [ "${LATEST}" -eq 1 ]; then
    dir="$(env_value BACKUP_DIR)"; dir="${dir:-${PROJECT_ROOT}/backups}"
    case "${dir}" in /*) ;; *) dir="${PROJECT_ROOT}/${dir#./}" ;; esac
    # shellcheck disable=SC2012 - names are generated by backup_selfhosted.sh
    FILE="$(ls -1t "${dir}"/sapdemo-*.dump 2>/dev/null | head -n 1 || true)"
    [ -n "${FILE}" ] || die "No backup found in ${dir}." 2
    info "Newest backup: ${FILE}"
fi

[ -n "${FILE}" ] || die "Give a backup with --file, or use --latest." 2
[ -f "${FILE}" ] || die "No such file: ${FILE}" 2

# ---------------------------------------------------------------------------
# Validate the file before touching any database
# ---------------------------------------------------------------------------
head -c 5 "${FILE}" | grep -q 'PGDMP' \
    || die "${FILE} is not a PostgreSQL custom-format dump." 2
ok "Dump header is valid."

if [ -f "${FILE}.sha256" ]; then
    dir="$(cd "$(dirname "${FILE}")" && pwd)"
    base="$(basename "${FILE}")"
    if command -v shasum >/dev/null 2>&1; then
        ( cd "${dir}" && shasum -a 256 -c "${base}.sha256" >/dev/null 2>&1 ) \
            || die "Checksum FAILED for ${FILE}. The file is corrupt or was modified. Refusing to restore it." 2
    elif command -v sha256sum >/dev/null 2>&1; then
        ( cd "${dir}" && sha256sum -c "${base}.sha256" >/dev/null 2>&1 ) \
            || die "Checksum FAILED for ${FILE}. Refusing to restore it." 2
    fi
    ok "Checksum verified."
else
    warn "No .sha256 beside this backup, so its integrity cannot be confirmed."
    warn "Restoring anyway, but treat the result with suspicion."
fi

[ "$(service_state database)" = "running" ] \
    || die "The database service is not running. Start the stack first." 2

# ---------------------------------------------------------------------------
# Throwaway verification - touches nothing live
# ---------------------------------------------------------------------------
if [ "${THROWAWAY}" -eq 1 ]; then
    scratch="sapdemo_restore_check_$$"
    info "Restoring into throwaway database '${scratch}'..."

    cleanup_scratch() {
        compose exec -T database psql -U "${db_user}" -d postgres \
            -c "DROP DATABASE IF EXISTS ${scratch}" >/dev/null 2>&1 || true
    }
    trap cleanup_scratch EXIT

    compose exec -T database psql -U "${db_user}" -d postgres \
        -c "CREATE DATABASE ${scratch}" >/dev/null \
        || die "Could not create the throwaway database."

    if ! compose exec -T database pg_restore \
            -U "${db_user}" -d "${scratch}" --no-owner --no-privileges < "${FILE}" >/dev/null 2>&1; then
        fail "pg_restore reported errors restoring into the throwaway database."
        exit 1
    fi

    tables="$(compose exec -T database psql -U "${db_user}" -d "${scratch}" -tAc \
        "SELECT count(*) FROM information_schema.tables WHERE table_schema='public'" 2>/dev/null | tr -d '[:space:]')"
    rows="$(compose exec -T database psql -U "${db_user}" -d "${scratch}" -tAc \
        "SELECT COALESCE(sum(n_live_tup), 0) FROM pg_stat_user_tables" 2>/dev/null | tr -d '[:space:]')"

    # A dump that restores into an empty schema is a dump of nothing. Saying
    # "restore succeeded" about it would be the exact false assurance this
    # script exists to prevent.
    if [ "${tables:-0}" -lt 5 ]; then
        fail "The restored database has only ${tables:-0} table(s). That is not a usable backup."
        exit 1
    fi

    ok "Restored ${tables} tables (~${rows:-0} rows) into the throwaway database."
    ok "The backup is restorable. The throwaway database is now dropped."
    exit 0
fi

# ---------------------------------------------------------------------------
# Live restore - destructive
# ---------------------------------------------------------------------------
printf '\n'
printf '  %sThis REPLACES the live demonstration database.%s\n' "${C_RED}" "${C_RESET}"
printf '  Target   %s\n' "${db_name}"
printf '  From     %s\n' "${FILE}"
printf '\n'
printf '  Everything currently in %s will be gone.\n' "${db_name}"
printf '\n'

if [ "${ASSUME_YES}" -ne 1 ]; then
    confirm "Restoring over a live database cannot be undone." "restore" \
        || { info "Nothing was changed."; exit 2; }
fi

# Take a safety copy first. Restoring the wrong backup is a normal mistake, and
# it is only unrecoverable if the thing it overwrote is gone.
safety="${PROJECT_ROOT}/backups/pre-restore-$(date -u +%Y%m%dT%H%M%SZ).dump"
mkdir -p "$(dirname "${safety}")"
info "Taking a safety copy of the current database first..."
if compose exec -T database pg_dump -U "${db_user}" -d "${db_name}" \
        -Fc --no-owner --no-privileges > "${safety}" 2>/dev/null \
   && [ "$(wc -c < "${safety}" | tr -d ' ')" -gt 1024 ]; then
    ok "Safety copy: ${safety}"
else
    rm -f "${safety}"
    warn "Could not take a safety copy (the database may be empty). Continuing."
fi

info "Stopping the services that hold connections..."
compose stop api streamlit >/dev/null 2>&1 || true

info "Recreating the database..."
compose exec -T database psql -U "${db_user}" -d postgres \
    -c "DROP DATABASE IF EXISTS ${db_name} WITH (FORCE)" >/dev/null \
    || die "Could not drop ${db_name}."
compose exec -T database psql -U "${db_user}" -d postgres \
    -c "CREATE DATABASE ${db_name}" >/dev/null \
    || die "Could not recreate ${db_name}."

info "Restoring..."
if ! compose exec -T database pg_restore \
        -U "${db_user}" -d "${db_name}" --no-owner --no-privileges < "${FILE}"; then
    fail "pg_restore reported errors."
    [ -f "${safety}" ] && printf '        The pre-restore copy is at %s\n' "${safety}" >&2
    compose start api streamlit >/dev/null 2>&1 || true
    exit 1
fi
ok "Restore completed."

info "Starting the services again..."
compose start api streamlit >/dev/null 2>&1 || warn "Start the stack by hand: ./scripts/start_selfhosted.sh"

wait_for_health api 600 || exit 1

printf '\n'
ok "The demonstration database has been restored from ${FILE}."
printf '  Verify:  ./scripts/verify_selfhosted.sh\n'
